# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20161030_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
